const vm_mod = @import("../vm.zig");

const VM = vm_mod.VM;

const array = @import("array.zig");
const basic_object = @import("basic_object.zig");
const class_builtin = @import("class.zig");
const encoding = @import("encoding.zig");
const enumerator = @import("enumerator.zig");
const env = @import("env.zig");
const exception = @import("exception.zig");
const false_class = @import("false_class.zig");
const dir = @import("dir.zig");
const enumerable = @import("enumerable.zig");
const file = @import("file.zig");
const float = @import("float.zig");
const hash = @import("hash.zig");
const io = @import("io.zig");
const integer = @import("integer.zig");
const kernel = @import("kernel.zig");
const match_data = @import("match_data.zig");
const module_builtin = @import("module.zig");
const nil_class = @import("nil_class.zig");
const object = @import("object.zig");
const proc_builtin = @import("proc.zig");
const process = @import("process.zig");
const fiber = @import("fiber.zig");
const thread = @import("thread.zig");
const mutex = @import("mutex.zig");
const queue = @import("queue.zig");
const time = @import("time.zig");
const warning = @import("warning.zig");
const range = @import("range.zig");
const regexp = @import("regexp.zig");
const socket = @import("socket.zig");
const struct_builtin = @import("struct.zig");
const string = @import("string.zig");
const symbol = @import("symbol.zig");
const true_class = @import("true_class.zig");

pub fn registerAll(vm: *VM) !void {
    try basic_object.register(vm);
    try kernel.register(vm);
    try object.register(vm);
    try class_builtin.register(vm);
    try module_builtin.register(vm);
    try integer.register(vm);
    try float.register(vm);
    try array.register(vm);
    try hash.register(vm);
    try io.register(vm);
    try file.register(vm);
    try dir.register(vm);
    try enumerable.register(vm);
    try env.register(vm);
    try process.register(vm);
    try warning.register(vm);
    try proc_builtin.register(vm);
    try struct_builtin.register(vm);
    try fiber.register(vm);
    try thread.register(vm);
    try mutex.register(vm);
    try queue.register(vm);
    try time.register(vm);
    try range.register(vm);
    try regexp.register(vm);
    try socket.register(vm);
    try match_data.register(vm);
    try string.register(vm);
    try symbol.register(vm);
    try nil_class.register(vm);
    try true_class.register(vm);
    try false_class.register(vm);
    try exception.register(vm);
    try encoding.register(vm);
    try enumerator.register(vm);
}
