"""Generate Cora's JIS mapping tables from MRI's transcode sources.

Run from the repository root with ../ruby checked out:
    python3 tools/generate_jis_tables.py
"""

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / "ruby" / "enc" / "trans" / "JIS"
OUTPUT = ROOT / "src" / "encoding" / "jis_tables.zig"
ENTRY = re.compile(r"^0x([0-9A-F]+) = 0x([0-9A-F]+)$", re.MULTILINE)


def mappings(name):
    return [(int(a, 16), int(b, 16)) for a, b in ENTRY.findall((SOURCE / name).read_text())]


def emit_array(lines, name, values, width):
    lines.append(f"pub const {name} = [_]u{width}{{")
    for start in range(0, len(values), 12):
        chunk = values[start : start + 12]
        lines.append("    " + ", ".join(f"0x{value:0{width // 4}X}" for value in chunk) + ",")
    lines.append("};")
    lines.append("")


lines = [
    "// Generated by tools/generate_jis_tables.py from MRI's JIS transcode sources.",
    "// Do not edit these mappings by hand.",
    "",
]
for plane, label in (("JISX0208@1990", "jis0208"), ("JISX0212", "jis0212")):
    decode = [0] * (94 * 94)
    for jis, unicode in mappings(f"{plane}%UCS.src"):
        row, col = jis >> 8, jis & 0xFF
        assert 0x21 <= row <= 0x7E and 0x21 <= col <= 0x7E
        assert unicode <= 0xFFFF
        decode[(row - 0x21) * 94 + col - 0x21] = unicode
    encode = sorted((unicode << 16) | jis for unicode, jis in mappings(f"UCS%{plane}.src"))
    assert len({entry >> 16 for entry in encode}) == len(encode)
    emit_array(lines, f"{label}_to_unicode", decode, 16)
    emit_array(lines, f"unicode_to_{label}", encode, 32)

OUTPUT.write_text("\n".join(lines))
