name: Test Gems

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-gems:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Zig
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29
        with:
          version: 0.16.0

      - name: Test gems
        run: zig build test-gems --summary all
